[Core]: Improved lost CF pruning
Open-Agriculture/AgIsoStack-plus-plus pull request #249
Opened 2023-04-29 20:45 UTC by ad3154

* Added active control function pruning so that if a control function fails to claim after a request for the address claim PGN, we move that control function to the inactive list and invalidate its address. 

This was always meant to be a part of how we manage address claiming, but for whatever reason got left behind. This greatly increases the reliability of checking a control function's address being valid.

* Fixed a random crash in unit tests.

Closes #192

2023-05-02 00:58 UTC, ad3154 commented
@GwnDaan Since this is linked to your issue originally, when you have time, I'd love a review

2023-05-04 08:43 UTC, GwnDaan commented
> @GwnDaan Since this is linked to your issue originally, when you have time, I'd love a review

Sounds good, it will still be a few days before I can do any testing or reviewing. But I'll be happy to test it when I get the time :)

2023-05-10 11:34 UTC, GwnDaan commented
Hi @ad3154, still seeing some weird behavior when trying to steal a CF:

To replicate, first start the version3_object_pool example (claims 0x1C):
![image](https://github.com/ad3154/Isobus-plus-plus/assets/29043784/ea8f48db-98f6-4345-b0d9-f2a607253cb3)

Then start the aux_inputs example (modified to claim 0x1C as well):
![image](https://github.com/ad3154/Isobus-plus-plus/assets/29043784/733bec23-b854-46bb-a255-960952a15e53)

But now the version3_object_pool example loses connection with the VT:
![image](https://github.com/ad3154/Isobus-plus-plus/assets/29043784/df3f59d0-9967-4865-a823-c1a294ef865a)

What are your thoughts?

2023-05-10 11:36 UTC, GwnDaan commented
The other way around fails now as well (at the time of creating #192 it worked fine IIRC):

Here I first started the` aux_input` example and then the `version3_object_pool` example:
![image](https://github.com/ad3154/Isobus-plus-plus/assets/29043784/edc0ddf1-fdee-421c-bb03-491a3459fb0c)

![image](https://github.com/ad3154/Isobus-plus-plus/assets/29043784/81337baa-4257-4c21-a6a1-04b170f90e6a)

2023-05-10 11:39 UTC, GwnDaan requested changes

2023-05-10 11:39 UTC, GwnDaan commented on isobus/src/can_address_claim_state_machine.cpp
> +						                      m_preferredAddress);
```suggestion
						CANStackLogger::debug("[AC]: Internal control function %016llx has claimed address %u on channel %u",
						                      m_isoname.get_full_name(),
						                      m_preferredAddress,
						                      m_portIndex);
```

2023-05-10 11:39 UTC, GwnDaan commented on isobus/src/can_address_claim_state_machine.cpp
> +							                      m_preferredAddress);
```suggestion
							CANStackLogger::debug("[AC]: Internal control function %016llx could not use the preferred address, but has claimed address %u on channel %u",
							                      m_isoname.get_full_name(),
							                      m_preferredAddress,
							                      m_portIndex);
```

2023-05-10 14:45 UTC, ad3154 commented
Thanks for the feedback! I will continue working on this...

2023-06-06 23:57 UTC, ad3154 commented
I think I've got all the issues worked out in here now.

In the following log output, you can see the VT example runs normally, and properly detects when I unplug a device from the bus.

![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/ac8115c2-3731-4641-8b1c-e63b38f219ab)

2023-06-07 00:56 UTC, ad3154 commented
Okay, now the unit test should be fixed as well. 🙂

2023-06-07 14:08 UTC, GwnDaan commented
> The other way around fails now as well (at the time of creating #192 it worked fine IIRC):
> 
> Here I first started the` aux_input` example and then the `version3_object_pool` example: ![image](https://user-images.githubusercontent.com/29043784/237378132-edc0ddf1-fdee-421c-bb03-491a3459fb0c.png)
> 
> ![image](https://user-images.githubusercontent.com/29043784/237378172-81337baa-4257-4c21-a6a1-04b170f90e6a.png)

I still partially have this issue. It seems that when the aux_inputs example get's kicked of it's preferred address, it just claims it's preferred address back again according to the logs:

`aux_inputs` example (started before `version3_object_pool`  example):
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/29043784/181704fa-535c-4448-b556-9ab3ba9aa51b)

`version3_object_pool` example logs (started right after the still running `aux_inputs` example):
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/29043784/b065c337-7f05-4e1e-b262-3e693a81da41)

2023-06-07 14:26 UTC, ad3154 commented
Yeah, that's not the right behavior - I'll take a look at that, thanks

2023-06-07 18:54 UTC, ad3154 commented
Looks like a logging issue... I was passing in the preferred address to that log statement instead of the loop variable.
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/8a079eef-e1e9-414a-9a28-c3100cf09669)

2023-06-07 20:31 UTC, GwnDaan commented
Hmm then the issue with the object pool might be out of the scope of this PR? Not sure if it's related to CF's

> `version3_object_pool` example logs (started right after the still running `aux_inputs` example):
> ![image](https://user-images.githubusercontent.com/29043784/244092782-b065c337-7f05-4e1e-b262-3e693a81da41.png)

2023-06-08 01:43 UTC, ad3154 commented
After recreating it and looking at a candump, it seems like the address claiming messages and process are correct, but looking at the address table in the network manager, there's definitely something sketchy going on, as the slot that should be the Vt Example's ICF is occupied by the external control function that moved to a different address. So although the correct messages were sent, our internal tracking of them seems to be confused. I've come this far with it, I might as well try and fix it before merging this in... 
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/0482be9b-5c40-4fc1-b83e-75975b87530a)

2023-06-09 01:49 UTC, ad3154 commented
Okay, now I think I've got it. Ready for re-review @GwnDaan 

![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/344a4ae0-1b7c-411a-8e7e-7c59f617d5b8)

2023-06-16 16:09 UTC, GwnDaan approved these changes

2023-06-17 05:34 UTC, merged