Add Windows and Mac OS builds
Open-Agriculture/AgIsoStack-plus-plus pull request #321
Opened 2023-09-06 23:06 UTC by ad3154

Added compilation checks for Windows and Mac platforms.

Part of #320

2023-09-06 23:24 UTC, ad3154 commented
It seems like the new checks didn't run here on the branch... unsure if that means they need to be in main first before we get real feedback?

2023-09-07 15:03 UTC, GwnDaan requested changes

2023-09-07 23:52 UTC, ad3154 commented on .github/workflows/build.yml
> +             submodules: recursive
Hmm, I still might be missing something, as I added the `ref: ${{ github.event.pull_request.head.sha }}` bit

2023-09-08 13:50 UTC, GwnDaan approved these changes
Yea, due to the nature of the 'pull_request_target' the CI seems to be from the base branch, hence your changes will only be applied to a next PR. Another downside of this trigger type 😅

2023-09-08 23:14 UTC, merged