[ETP]: Rewrite to match with other transport protocols
Open-Agriculture/AgIsoStack-plus-plus pull request #391
Opened 2023-12-20 08:45 UTC by GwnDaan

This PR includes a full rewrite of the extended transport protocol where I've taken the rewrite of the TP as base

2024-01-06 18:34 UTC, ad3154 commented
I did try testing our VT example against our VT, and got a crash in the VT example here:

![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/d982d5e8-1bc4-4183-bbaf-636701f7b24b)

Buffer size was 0

Callstack:

```
 	VT3ExampleTarget.exe!std::vector<unsigned char,std::allocator<unsigned char>>::operator[](const unsigned __int64 _Pos) Line 1893	C++
 	VT3ExampleTarget.exe!isobus::CANMessageDataCallback::get_byte(unsigned __int64 index) Line 107	C++
	VT3ExampleTarget.exe!isobus::ExtendedTransportProtocolManager::send_data_transfer_packets(std::shared_ptr<isobus::ExtendedTransportProtocolManager::ExtendedTransportProtocolSession> & session) Line 596	C++
 	VT3ExampleTarget.exe!isobus::ExtendedTransportProtocolManager::update_state_machine(std::shared_ptr<isobus::ExtendedTransportProtocolManager::ExtendedTransportProtocolSession> & session) Line 696	C++
 	VT3ExampleTarget.exe!isobus::ExtendedTransportProtocolManager::update() Line 571	C++
 	VT3ExampleTarget.exe!isobus::CANNetworkManager::update() Line 249	C++
 	VT3ExampleTarget.exe!isobus::periodic_update_from_hardware() Line 304	C++
 	VT3ExampleTarget.exe!isobus::CANHardwareInterface::update_thread_function() Line 297	C++

```

![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/64e6ac88-3e44-42cf-9d8a-3d46b48701ee)

2024-01-06 19:06 UTC, ad3154 requested changes

2024-01-06 19:06 UTC, ad3154 commented on isobus/src/can_message_data.cpp
> +} // namespace isobus
Nit: missing newline at end of file

2024-01-06 19:06 UTC, ad3154 commented on isobus/src/can_transport_protocol_base.cpp
> +		return static_cast<float>(get_total_bytes_transferred()) / static_cast<float>(get_message_length());
Nit: Technically to be a percentage this would have to be `* 100` otherwise it's just the fraction

2024-01-06 19:06 UTC, ad3154 commented on isobus/src/can_transport_protocol_base.cpp
> +		return static_cast<float>(get_total_bytes_transferred()) / static_cast<float>(get_message_length());
Also.... paranoid brain, should check `0 != get_message_length()` to avoid `NaN`?

2024-01-06 19:06 UTC, ad3154 commented on isobus/src/can_transport_protocol_base.cpp
> +}
Nit: missing newline at end of file

2024-01-06 19:27 UTC, GwnDaan commented on isobus/include/isobus/isobus/can_network_configuration.hpp
> +		std::uint8_t numberOfPacketsPerCTSMessage = 16; ///< The number of packets per CTS message for TP sessions
Yeah I agree, though it's the recommendation of the standard (section 5.13.6)

2024-01-06 19:29 UTC, GwnDaan commented on isobus/include/isobus/isobus/can_transport_protocol.hpp
> +		static constexpr std::uint32_t CONNECTION_ABORT_MULTIPLEXOR = 255; ///< Abort multiplexor
Ahh ofcourse, in the standard it's defined in the decimal format so exactly the other way around 😂. I'll add comments with the hexadecimal variant

2024-01-06 19:30 UTC, ad3154 commented on isobus/include/isobus/isobus/can_transport_protocol.hpp
> +		static constexpr std::uint32_t CONNECTION_ABORT_MULTIPLEXOR = 255; ///< Abort multiplexor
Yeah, comment works for me, sounds good

2024-01-06 19:31 UTC, ad3154 commented on isobus/include/isobus/isobus/can_network_configuration.hpp
> +		std::uint8_t numberOfPacketsPerCTSMessage = 16; ///< The number of packets per CTS message for TP sessions
Well..... huh I guess it does say that. As long as it's changeable I guess its fine then haha

2024-01-07 14:22 UTC, GwnDaan commented
Good catch! I fixed that issue, and resolved your comments. Also fixed a few other small issues

2024-01-15 01:37 UTC, ad3154 commented
There is still some callback issue....  when I run the VT example, I can see situations where the callback gets called with a buffer of size 0, so when the callback tries to memcpy the data into it, that probably doesn't do anythign, and the end result later is an exception when we try to index into a 0 size buffer 

![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/05ee14fd-7a1d-41f3-8cfc-5d4198aed48e)

2024-01-15 12:41 UTC, GwnDaan commented
> buffer of size 0

Ahh my bad, I accidentally used `reserve` on the buffer instead of actually resizing the buffer. GCC didn't complain about it, but it was indeed not correct. It is fixed now

2024-01-15 23:16 UTC, ad3154 commented
Not crashing anymore with the VT or seeder example which is good. TP broadcast data message timing seems a bit long, like usually > 60ms which is curious but not super concerning.

Transport layer example needs a few updates to display 0-100 again.

![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/10929341/d763aa86-38e1-4c3e-9873-13ebdfb28a12)

2024-01-16 19:34 UTC, GwnDaan commented
> TP broadcast data message timing seems a bit long, like usually > 60ms which is curious but not super concerning.

Hmm that's weird, in the unit test `BroadcastMessageSending` it seems to think it is sending the frames within +/- 50ms:
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/29043784/e58acda1-490a-46d3-840e-1a693e74d075)

For me with vcan it seems to be pretty consistent 52ms inbetween frames (according to candump)
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/29043784/99fba796-f3b2-4316-987d-40407d3becb4)

Considering we are using a 4ms update loop by default, that seems okay:
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/29043784/166cd925-cb2a-4c37-801e-9ad6c8260bd7)

I make a guess that you use a lower update speed?

2024-01-17 18:54 UTC, ad3154 approved these changes

2024-01-18 19:00 UTC, merged